const cases={
 mayflower:{kicker:'Mayflower · Product design',title:'A calmer way to triage resident feedback.',lead:'A 10-week UX project for an Australian elder-care organisation, focused on helping administrators understand, prioritise and respond to resident and family feedback.',stats:[['10 weeks','Project'],['Desktop + mobile','Prototype'],['End-to-end','UX process']],sections:[['The challenge','Feedback and queries can arrive through different channels, with varying urgency and context. The design needed to help staff identify what mattered, understand ownership and move items toward resolution without creating more administrative burden.'],['What I did','I created the research plan, persona and task flows, explored low-fidelity concepts, developed responsive high-fidelity designs in Figma, built reusable components and prepared usability test scripts for desktop and mobile.'],['Key design decisions','Priority and status were surfaced early, repetitive information was grouped into scannable cards, and the workflow was designed around the admin’s next action rather than around system fields. The mobile experience was simplified to protect task clarity on smaller screens.'],['Outcome','The final prototype gave the team a clearer structure for triage, ownership and follow-up, with a consistent design system ready for developer handoff.']]},
 zenergy:{kicker:'Z Energy · UX redesign',title:'Helping drivers find the right station faster.',lead:'A responsive UX redesign focused on service filtering, fuel information and reducing comparison friction.',stats:[['Mobile + desktop','Surfaces'],['Service filters','Core flow'],['Figma','Prototype']],sections:[['Problem','The existing experience made it harder than necessary to compare stations and understand which services or fuel options were available at each location.'],['Approach','I mapped the station-finding journey, identified high-friction moments, simplified filter behaviour and explored how fuel and service information could be surfaced earlier.'],['Design response','The redesign prioritised location search, filter visibility and scannable station cards, with a tighter hierarchy on mobile so users could decide without opening multiple detail screens.'],['Learning','The project reinforced how much perceived complexity can be reduced through information hierarchy alone, before adding new functionality.']]},
 turners:{kicker:'Turners Insurance · Discovery',title:'Making insurance feel easier to understand.',lead:'A discovery and UX exploration around confidence, comparison and progression through insurance journeys.',stats:[['Discovery','Phase'],['Insurance','Domain'],['Clarity','Design goal']],sections:[['Opportunity','Insurance experiences can overwhelm users with unfamiliar terms, long forms and uncertainty about what happens next.'],['What I explored','I reviewed key journeys, looked for moments where language or hierarchy could create hesitation and identified opportunities to improve progression, reassurance and comparison.'],['Design principles','Use plain language, explain why information is needed, keep the next step obvious and avoid showing detail before it becomes relevant.'],['Value','The work created a clearer set of UX priorities that could guide future interaction and content design decisions.']]},
 council:{kicker:'Auckland Council · UX audit',title:'Reducing friction in local service tasks.',lead:'A UX audit focused on issue reporting and inorganic collection journeys, especially on mobile.',stats:[['UX audit','Method'],['Mobile-first','Focus'],['Council services','Domain']],sections:[['Problem','Council service journeys often contain policy detail, eligibility rules and multi-step forms. Users still need to complete simple tasks quickly.'],['Audit focus','I reviewed task clarity, content hierarchy, navigation, form progression and mobile usability, identifying where information or controls competed with the user’s primary goal.'],['Recommendations','Bring task-critical information forward, simplify page hierarchy, reduce repeated instructions and use progressive disclosure for policy detail that is not immediately required.'],['Impact','The audit produced a clearer direction for a more understandable and task-focused council service experience.']]}
};
const modal=document.getElementById('caseModal');const content=document.getElementById('caseContent');
document.querySelectorAll('[data-project]').forEach(btn=>btn.addEventListener('click',()=>{const c=cases[btn.dataset.project];content.innerHTML=`<span class="case-kicker">${c.kicker}</span><h2 id="caseTitle">${c.title}</h2><p class="lead">${c.lead}</p><div class="case-stat-row">${c.stats.map(s=>`<div><b>${s[0]}</b><small>${s[1]}</small></div>`).join('')}</div>${c.sections.map(s=>`<section><h4>${s[0]}</h4><p>${s[1]}</p></section>`).join('')}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
modal.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open')){modal.classList.remove('open');document.body.style.overflow=''}});
